import { createStore } from "vuex";

const store = createStore({
    state: {
        user: { data: { name: "Hello, Singko!" }, token: null },
        categories: {
            food: [
                "99 Meals & Single Orders",
                "Soup",
                "Pizza",
                "Sandwiches",
                "Sides & Add Ons",
            ],
            drinks: [
                "Milktea & Frappe",
                "Smoothies & Milkshake",
                "Yogurt & Coffee",
                "Lemonade & Fruitea",
                "Others",
            ],
        },
        addons: [
            "Tapioca",
            "Nata",
            "Oreo",
            "Coffee Jelly",
            "Pudding",
            "Red Bean",
            "Cream Cheese",
            "Cheese Cake",
        ],
        cart: [
            {
                name: "Dark Chocolate",
                category: "Milktea",
                quantity: 1,
                size: "22oz",
                sugar: "50%",
                price: 149.0,
                adds: ["Tapioca", "Red Bean", "Cream Cheese"],
            },
            {
                name: "Dark Chocolate",
                category: "Milktea",
                quantity: 1,
                size: "22oz",
                sugar: "50%",
                price: 149.0,
                adds: ["Tapioca", "Red Bean", "Cream Cheese"],
            },
            {
                name: "Dark Chocolate",
                category: "Milktea",
                quantity: 1,
                size: "22oz",
                sugar: "50%",
                price: 149.0,
                adds: ["Tapioca", "Red Bean", "Cream Cheese"],
            },
            {
                name: "Dark Chocolate",
                category: "Milktea",
                quantity: 1,
                size: "22oz",
                sugar: "50%",
                price: 149.0,
                adds: ["Tapioca", "Red Bean", "Cream Cheese"],
            },
            {
                name: "Dark Chocolate",
                category: "Milktea",
                quantity: 1,
                size: "22oz",
                sugar: "50%",
                price: 149.0,
                adds: ["Tapioca", "Red Bean", "Cream Cheese"],
            },
            {
                name: "Dark Chocolate",
                category: "Milktea",
                quantity: 1,
                size: "22oz",
                sugar: "50%",
                price: 149.0,
                adds: ["Tapioca", "Red Bean", "Cream Cheese"],
            },
            {
                name: "Dark Chocolate",
                category: "Milktea",
                quantity: 1,
                size: "22oz",
                sugar: "50%",
                price: 149.0,
                adds: ["Tapioca", "Red Bean", "Cream Cheese"],
            },
            {
                name: "Dark Chocolate",
                category: "Milktea",
                quantity: 1,
                size: "22oz",
                sugar: "50%",
                price: 149.0,
                adds: ["Tapioca", "Red Bean", "Cream Cheese"],
            },
            {
                name: "Dark Chocolate",
                category: "Milktea",
                quantity: 1,
                size: "22oz",
                sugar: "50%",
                price: 149.0,
                adds: ["Tapioca", "Red Bean", "Cream Cheese"],
            },
            {
                name: "Dark Chocolate",
                category: "Milktea",
                quantity: 1,
                size: "22oz",
                sugar: "50%",
                price: 149.0,
                adds: ["Tapioca", "Red Bean", "Cream Cheese"],
            },
            {
                name: "Dark Chocolate",
                category: "Milktea",
                quantity: 1,
                size: "22oz",
                sugar: "50%",
                price: 149.0,
                adds: ["Tapioca", "Red Bean", "Cream Cheese"],
            },
            {
                name: "Dark Chocolate",
                category: "Milktea",
                quantity: 1,
                size: "22oz",
                sugar: "50%",
                price: 149.0,
                adds: ["Tapioca", "Red Bean", "Cream Cheese"],
            },
        ],
    },
    getters: {},
    actions: {},
    mutations: {},
    modules: {},
});

export default store;
